In [1]:
import gym
import fetch
import numpy as np
from fetch import wrappers

from stable_baselines.sac.policies import MlpPolicy
from stable_baselines import SAC

env = gym.make('FetchReachNewDense-v1')
env = wrappers.TransformObservation(env)
obs = env.reset()
print(obs)
action = env.action_space.sample()
obs, reward, done,info = env.step(action)

print(reward)

/home/ughni/.Envs/venv_mujoco/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ughni/.Envs/venv_mujoco/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ughni/.Envs/venv_mujoco/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ughni/.Envs/venv_mujoco/lib/python3.6/site-packages/ten

Creating window glfw
[[[133  60 121]
  [133  60 121]
  [ 57 141 213]
  ...
  [133  59 121]
  [133  59 121]
  [133  59 121]]

 [[135  60 119]
  [ 86 122 190]
  [ 43 169 247]
  ...
  [134  60 120]
  [134  60 120]
  [134  60 120]]

 [[103 101 165]
  [ 42 167 245]
  [ 52 179 255]
  ...
  [135  60 119]
  [135  60 119]
  [135  60 119]]

 ...

 [[142 143 148]
  [142 144 148]
  [142 144 149]
  ...
  [ 65  65  65]
  [ 65  65  65]
  [ 65  65  65]]

 [[142 144 149]
  [142 144 149]
  [142 144 149]
  ...
  [ 65  65  65]
  [ 65  65  65]
  [ 65  65  65]]

 [[142 144 149]
  [143 144 149]
  [143 144 149]
  ...
  [ 65  65  65]
  [ 65  65  65]
  [ 65  65  65]]]
-0.1126993213588947


In [ ]:
model = SAC(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=50000, log_interval=10)
model.save("sac_pendulum")

del model # remove to demonstrate saving and loading

model = SAC.load("sac_pendulum")

obs = env.reset()
x = 0
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()